#端口
server:  
  port: 9001

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always  

spring:  
  boot:  
    admin:  
      notify:  
        mail:  
          enabled: false
          to: zhangzhengdong@key-win.net
          from: zhangzhengdong@key-win.net
#          ignore-changes: UNKNOWN:UP  
          ignore-changes:  
            -  
              "*:UP" #从任何状态到up状态都不要发邮件通知  
      routes:  
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
      turbine:
        clusters: default
        #,unieap-eureka-server-single
        location: turbine  
  mail:
    host: smtp.key-win.net
    username: zhangzhengdong@key-win.net
    password: Fkshl@412.cn.com
    properties:
        mail.smtp.auth : true
        mail.smtp.timeout : 2000
        mail.smtp.starttls.enable : true
        mail.smtp.starttls.required : true 

#设置最大超时时间
ribbon:  
  eager-load:
    enabled: true
  ServerListRefreshInterval: 10  #刷新服务列表源的间隔时间
  OkToRetryOnAllOperations: true
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1
  ReadTimeout: 16000  
  ConnectTimeout: 16000 
  
  