# 注册中心 
spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr} ### nacos server地址127.0.0.1:8848
        namespace: ${spring.cloud.nacos.config.namespace}  #命名空间 代指某个环境
        group: ${spring.cloud.nacos.config.group} ###DEV_GROUP
    sentinel:
      transport:
        # 指定sentinel 控制台的地址
        dashboard: 127.0.0.1:8080
      eager: true
  jackson:
    mapper:
      ALLOW_EXPLICIT_PROPERTY_RENAMING: true
    deserialization:
      READ_DATE_TIMESTAMPS_AS_NANOSECONDS: false
    serialization:
      WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS: false
      WRITE_DATES_AS_TIMESTAMPS: true
#metrics
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    chaosmonkey:
      enabled: true
    health:
      show-details: always
